name: Run stack

on:
  # schedule:
  #   - cron: '0 0,6,12,18 * * *'  
    
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-job]

# concurrency:
#   group: n8n
#   cancel-in-progress: false
  
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    env:
      DB_POSTGRESDB_HOST: ${{ secrets.DB_POSTGRESDB_HOST }}
      DB_POSTGRESDB_PORT: ${{ secrets.DB_POSTGRESDB_PORT }}
      DB_POSTGRESDB_DATABASE: ${{ secrets.DB_POSTGRESDB_DATABASE }}
      DB_POSTGRESDB_USER: ${{ secrets.DB_POSTGRESDB_USER }}
      DB_POSTGRESDB_PASSWORD: ${{ secrets.DB_POSTGRESDB_PASSWORD }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
      R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore secrets (certs & argo)
        run: |
          mkdir -p ~/aiven ~/cloudflare ~/db
          echo "${{ secrets.CA_PEM_B64 }}" | base64 -d > ~/aiven/ca.pem
          echo "${{ secrets.ARGO_YML_B64 }}" | base64 -d > ~/cloudflare/argo.yml
          echo "${{ secrets.ARGO_JSON_B64 }}" | base64 -d > ~/cloudflare/argo.json
      
      - name: Download previous DB
        uses: actions/download-artifact@v5
        with:
          name: db
          path: /home/runner/db
        continue-on-error: true

      # - name: Cache Docker images.
      #   uses: AndreKurait/docker-cache@0.6.0
      #   with:
      #     key: docker-${{ runner.os }}-${{ hashFiles('n8n.yml') }}

      - name: Run docker-compose
        run: |
          docker compose -f n8n.yml up -d

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600

      - name: Do your work
        run: |
          echo "Running job at $(date)"
          sleep 5.8h
          
      - name: backup DB
        uses: actions/upload-artifact@v4
        with:
          name: db
          path: /home/runner/db
          retention-days: 90
          compression-level: 6
          
      - name: Trigger next run
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"deploy-job"}'
          
